Fix create_llvm_prof to use discriminator encoding for LLVM version 5.0 and above
commit f7ee8285dee "Make create_llvm_prof to use discriminator encoding" tried
to fix commit commit 72b7f86b920 "Rebase autofdo toolchain", which added
enhanced discriminator support, added in LLVM version 5.  The latter added it
in such a way that create_llvm_prof was not built correctly (presumably when
built by gcc), which would - again, presumably - allow users feed
enhanced discriminator input to a create_llvm_prof binary that couldn't read
the enhanced data, which ultimately led to imprecise or wrong output data.

commit f7ee8285dee "Make create_llvm_prof to use discriminator encoding" went
further and added a new CREATE_LLVM_PROF define to the build system to protect
build breakage from building non-LLVM targets

The only files that include source_info.h are: addr2line.h, symbol_map.h, and
source_info.cc, each of which include "base/common.h" before they include
"source_info.h".  base/common.h...where is it???  compiler -DHAVE_LLVM?

    Now LLVM debug metadata uses discriminator to express not only
    multiple expressions in a single line, but also other optimization
    information such as unrolling factor. Therefore, create_llvm_prof needs
    to be in accordance with this to provide precise discriminator info.

    In source_info.h file, which is updated by this diff, checks if
    HAVE_LLVM is defined to decide if discriminator encoding needs to be
    supported or not. However, the file that define HAVE_LLVM (config.h) has
    not been included by source_info.h. This made create_llvm_prof
    to generate wrong profile data that are ignorant about discriminator
    encoding.

    Simply including config.h from source_info.h breaks the build, because
    the same file (source_info.h) is used by create_gcov as well, which has
    no idea about LLVM at all (Other files checking HAVE_LLVM are only used
    by create_llvm_prof). To prevent this, -DCREATE_LLVM_PROF is added to
    CXXFLAGS for create_llvm_prof build, and make source_info.h to check
    CREATE_LLVM_PROF as well.

To reproduce the error, bleach the autofdo project using:

make maintainer-clean  FIXME - see attached bleach.sh

might have to:
+include <cstdio>
+include "llvm/Config/llvm-config.h"
+

Then install a version of llvm lower than 5.0 (and remove any 5.0 and above versions laying around),

In file included from addr2line.h:24:0,
                 from addr2line.cc:17:
source_info.h: In member function 'uint32 autofdo::SourceInfo::Offset(bool) const':
source_info.h:63:19: error: 'getBaseDiscriminatorFromDiscriminator' is not a member of 'llvm::DILocation'
                 ? llvm::DILocation::getBaseDiscriminatorFromDiscriminator(
                   ^
source_info.h: In member function 'uint32 autofdo::SourceInfo::DuplicationFactor() const':
source_info.h:73:12: error: 'getDuplicationFactorFromDiscriminator' is not a member of 'llvm::DILocation'
     return llvm::DILocation::getDuplicationFactorFromDiscriminator(
            ^
make[1]: *** [Makefile:925: create_llvm_prof-addr2line.o] Error 1

For gentoo user:

theirs doesn't -DCREATE_LLVM_PROF:

x86_64-pc-linux-gnu-
g++ -DHAVE_CONFIG_H -I. -I./glog/src -I. -I./glog/src -I/usr/lib64/llvm/4/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -march=native -O2 -pipe -c -o create_llvm_prof-addr2line.o `test -f 'addr2line.cc' || echo './'`addr2line.cc

Ubuntu does:

g++ -DHAVE_CONFIG_H -I. -I./glog/src  -I. -I./glog/src  -I/usr/include            -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DCREATE_LLVM_PROF -g -O2 -std=gnu++11 -MT create_llvm_prof-addr2line.o -MD -MP -MF .deps/create_llvm_prof-addr2line.Tpo -c -o create_llvm_prof-addr2line.o `test -f 'addr2line.cc' || echo './'`addr2line.cc

and gets:

In file included from addr2line.h:24:0,
                 from addr2line.cc:17:
source_info.h: In member function 'uint32 autofdo::SourceInfo::Offset(bool) const':
source_info.h:63:19: error: 'getBaseDiscriminatorFromDiscriminator' is not a member of 'llvm::DILocation'
                 ? llvm::DILocation::getBaseDiscriminatorFromDiscriminator(
                   ^
source_info.h: In member function 'uint32 autofdo::SourceInfo::DuplicationFactor() const':
source_info.h:73:12: error: 'getDuplicationFactorFromDiscriminator' is not a member of 'llvm::DILocation'
     return llvm::DILocation::getDuplicationFactorFromDiscriminator(
            ^
make[1]: *** [Makefile:925: create_llvm_prof-addr2line.o] Error 1

Cc: Taewook Oh <twoh@fb.com>
Signed-off-by: Kim Phillips <kim.phillips@arm.com>