m4/ax_llvm.m4: update configure's LLVM library test to match new LLVM 5 discriminator support dependency
Commit 72b7f86b920 "Rebase autofdo toolchain", added enhanced
discriminator support, which depends on LLVM version 5 and above.

Commit f7ee8285dee "Make create_llvm_prof to use discriminator encoding"
mentions possible imprecision bugs arising from mixing LLVM generated
version objects with autofdo create_llvm_prof built against a different
LLVM library version.

When building on a system with installed LLVM libraries older
than LLVM 5, we see the newly dependent code fail to build, with:

g++ -DHAVE_CONFIG_H -I. -I./glog/src  -I. -I./glog/src  -I/usr/lib/llvm-4.0/include   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DCREATE_LLVM_PROF -g -O2 -MT create_llvm_prof-sample_reader.o -MD -MP -MF .deps/create_llvm_prof-sample_reader.Tpo -c -o create_llvm_prof-sample_reader.o `test -f 'sample_reader.cc' || echo './'`sample_reader.cc
In file included from addr2line.h:24:0,
                 from addr2line.cc:17:
source_info.h: In member function ‘uint32 autofdo::SourceInfo::Offset(bool) const’:
source_info.h:63:37: error: ‘getBaseDiscriminatorFromDiscriminator’ is not a member of ‘llvm::DILocation’
                 ? llvm::DILocation::getBaseDiscriminatorFromDiscriminator(
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
source_info.h: In member function ‘uint32 autofdo::SourceInfo::DuplicationFactor() const’:
source_info.h:73:30: error: ‘getDuplicationFactorFromDiscriminator’ is not a member of ‘llvm::DILocation’
     return llvm::DILocation::getDuplicationFactorFromDiscriminator(
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...

We can't protect that code by adding a preprocessor check for
LLVM_VERSION_MAJOR >= 5, because create_llvm_prof is built with gcc.

So let's just add detection for getBaseDiscriminatorFromDiscriminator and
getDuplicationFactorFromDiscriminator to the existing configure test when
trying to determine whether to build create_llvm_prof with HAVE_LLVM set.
Otherwise, even though a create_llvm_prof binary is built, it won't run.

Signed-off-by: Kim Phillips <kim.phillips@arm.com>