configure.ac: enforce llvm 5 depencency
Since commit 72b7f86b "Rebase autofdo toolchain.", source_info.h uses
getBaseDiscriminatorFromDiscriminator and getDuplicationFactorFromDiscriminator
which are only available in llvm 5:

$ find /usr/include/ -name DebugInfoMetadata.h  | xargs grep -c getDuplicationFactorFromDiscriminator
/usr/include/llvm-4.0/llvm/IR/DebugInfoMetadata.h:0
/usr/include/llvm-3.8/llvm/IR/DebugInfoMetadata.h:0
/usr/include/llvm-5.0/llvm/IR/DebugInfoMetadata.h:2

Users on modern distros that don't know to upgrade their machines' LLVM
version from the default without ./configure --with-llvm=llvm-config-5.0
fail to build autofdo with a seemingly unrelated error:

g++ -DHAVE_CONFIG_H -I. -I./glog/src  -I. -I./glog/src  -I/usr/lib/llvm-4.0/include   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DCREATE_LLVM_PROF -g -O2 -MT create_llvm_prof-source_info.o -MD -MP -MF .deps/create_llvm_prof-source_info.Tpo -c -o create_llvm_prof-source_info.o `test -f 'source_info.cc' || echo './'`source_info.cc
In file included from addr2line.h:24:0,
                 from addr2line.cc:17:
source_info.h: In member function ‘uint32 autofdo::SourceInfo::Offset(bool) const’:
source_info.h:57:37: error: ‘getBaseDiscriminatorFromDiscriminator’ is not a member of ‘llvm::DILocation’
                 ? llvm::DILocation::getBaseDiscriminatorFromDiscriminator(
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
source_info.h: In member function ‘uint32 autofdo::SourceInfo::DuplicationFactor() const’:
source_info.h:67:30: error: ‘getDuplicationFactorFromDiscriminator’ is not a member of ‘llvm::DILocation’
     return llvm::DILocation::getDuplicationFactorFromDiscriminator(
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

fixes? issue 55, assuming the absolute dependency is valid.

how to get configure to enforce, however?
Fixes: 72b7f86b "Rebase autofdo toolchain."